# Traefik Dynamic Configuration
tls:
  certificates:
    - certFile: /certs/localhost-cert.pem
      keyFile: /certs/localhost-key.pem
  
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
